########################################################################################################

ZIMBRA_THIRDPARTY_SERVER = zdev-vm008.eng.zimbra.com

stage-zimbra-drive: downloads/zimbradrive-extension.jar downloads/zal-dev-drive.jar downloads/com_zextras_drive_open.zip
	install -T -D  downloads/zimbradrive-extension.jar  $(STAGE_DIR)/opt/zimbra/lib/ext/zimbradrive/zimbradrive-extension.jar
	install -T -D  downloads/zal-dev-drive.jar          $(STAGE_DIR)/opt/zimbra/lib/ext/zimbradrive/zal-dev.jar
	install -T -D  downloads/com_zextras_drive_open.zip $(STAGE_DIR)/opt/zimbra/zimlets/com_zextras_drive_open.zip

downloads/zimbradrive-extension.jar:
	mkdir -p downloads
	wget -O $@ http://$(ZIMBRA_THIRDPARTY_SERVER)/ZimbraThirdParty/zextras/zimbradrive-extension.jar

downloads/com_zextras_drive_open.zip:
	mkdir -p downloads
	wget -O $@ http://$(ZIMBRA_THIRDPARTY_SERVER)/ZimbraThirdParty/zextras/com_zextras_drive_open.zip

downloads/zal-dev-drive.jar:
	mkdir -p downloads
	wget -O $@ http://$(ZIMBRA_THIRDPARTY_SERVER)/ZimbraThirdParty/zextras/zal-dev.jar

########################################################################################################
